### ISSUE TITLE
Games with dots in their name only show the text before the first dot

### ISSUE THREAD

**Issue by ahco** [AndrewDWhite/GalaxyGenericImporterPlugin#76]
If the gam name has dots like B.A.T., the plugin only return B as a name.

I solve the issue using:
        {
            "name" : "Amiga",
            "execution" : "\"D:\\Emulation\\RetroArch\\retroarch.exe\" -f -L \"D:\\Emulation\\RetroArch\\cores\\puae_libretro.dll\" \"%ROM_RAW%\"",
            "path_regex" : ["D:\\Applications et jeux\\Amiga"],
            "tags" : ["Amiga"],
            "game_name_regex" : ".*[\\\\](.+?)([\\(\\[].*)*[.][^\\.]+$",
            "game_name_regex_group" : 1,
            "system_rom_name_regex_group" : 1,
            "filename_regex" : ["*[.]lha","*[.]zip"],
            "gameShouldBeInstalled" : true,
            "hashContent" : false
        },

It's an exemple for my Amiga games using Retroarch. It works for other platforms

**Comment by AndrewDWhite** [comment]
Updated the default examples to remove this feature breaking these in the dev branch. See the following for the preview build. Additionally, you may need to disconnect and reconnect the plugin for it to be reflected. https://github.com/AndrewDWhite/GalaxyGenericImporterPlugin/releases/tag/Prototype_a3862407cd827adc53181045416009a35666e310
![image](https://user-images.githubusercontent.com/972757/113466347-100f8080-9409-11eb-9960-a02bee7d95ce.png)
